name: t3_vault
description: "The T3 Vault cross platform application."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.1.0-dev

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  go_router: ^14.2.3
  great_wall:
    git:
      url: https://github.com/T3-InfoSec/great-wall-dart.git
      ref: formosa_integration
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
