name: t3_vault
description: "The T3 Vault cross platform application."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.1.0-dev

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  memory_assistant:
    git:
      url: https://github.com/T3-InfoSec/t3-memassist.git
      ref: migrate_main_logic

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
