name: t3_vault
description: "The T3 Vault cross platform application."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.1.0-dev

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  go_router: ^14.2.3
  great_wall:
#    git:
#      url: https://github.com/T3-InfoSec/great-wall-dart.git
#      ref: dart_migration_and_initialization
# This local path configuration is intended for development and testing purposes only. 
# Once the development phase is complete, it's recommended to switch to the GitHub repository version of this package.
    path: ../../dart/great-wall-dart 
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
