name: t3_vault
description: The T3 Vault cross platform application.
version: 1.0.0-dev
homepage: https://t3infosecurity.com
publish_to: 'none'

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  go_router: ^14.2.3
  path_provider: ^2.1.4
  uuid: ^3.0.6
  cryptography: ^2.7.0
  provider: ^6.1.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  android_intent_plus: ^5.2.0
  t3_formosa:
    git:
      url: git@github.com:T3-InfoSec/t3-formosa-dart.git
      ref: issue51_object_orient_cryptogaphic_objects_improvement
  great_wall:
    git:
      url: git@github.com:T3-InfoSec/great-wall-dart.git
      ref: issue51_object_orient_cryptogaphic_objects_improvement
  t3_memassist:
    git:
      url: git@github.com:T3-InfoSec/t3-memassist.git
      ref: issue51_object_orient_cryptogaphic_objects_improvement
  t3_crypto_objects:
    git:
      url: git@github.com:T3-InfoSec/t3-crypto-objects-dart.git
      ref: initialise_objects

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
