name: t3_vault
description: The T3 Vault cross platform application.
version: 0.1.0-dev
homepage: https://t3infosecurity.com
publish_to: 'none'

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  go_router: ^14.2.3
  t3_formosa:
    git:
      url: https://github.com/T3-InfoSec/t3-formosa-dart.git
      ref: initial_commit
  great_wall:
    git:
      url: https://github.com/T3-InfoSec/great-wall-dart.git
      ref: formosa_integration
  t3_memassist:
    git:
      url: https://github.com/T3-InfoSec/t3-memassist.git
      ref: migrate_main_logic

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
